package template.adm;

import Sources.transationCell;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import Sources.denunCell;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natanael-PC
 */
public class funcAccont extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(funcAccont.class.getName());

    /**
     * Creates new form historico
     */
    public static funcAccont funcScreen;
    
    public funcAccont() {
        initComponents();
        funcScreen = this;
        
        
        String clienteName = "usuário";
        hello.setText("Olá, "+ clienteName);
        
        int verticalGap = 10; // gap entre as celulas
        
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));
        
        denunCell cell[] = {new denunCell("000", "02/02/2002", 1),new denunCell("000", "02/02/2002", 2),new denunCell("000", "02/02/2002", 3)};
        //denunciado: //data //id:
        
        
        
        //adiciona as celulas
        int alturaTotal = ((60 + verticalGap))* (cell.length + 1);
        content.setPreferredSize(new Dimension(400, alturaTotal));
        for(denunCell currentCell : cell){
            content.add(Box.createVerticalStrut(verticalGap));
            content.add(currentCell);
            
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        header = new javax.swing.JPanel();
        hello = new javax.swing.JLabel();
        gradient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(102, 102, 102));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Denuncias");
        title.setToolTipText("");
        title.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().add(title);
        title.setBounds(10, 190, 1040, 30);

        content.setLayout(null);
        scroll.setViewportView(content);

        getContentPane().add(scroll);
        scroll.setBounds(0, 270, 1070, 620);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 230, 1040, 10);

        header.setBackground(new java.awt.Color(255, 69, 69));
        header.setLayout(null);

        hello.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        hello.setForeground(new java.awt.Color(255, 255, 255));
        hello.setText("Olá, {user}");
        hello.setToolTipText("");
        hello.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        header.add(hello);
        hello.setBounds(20, 30, 250, 78);

        gradient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/red_bg.jpg"))); // NOI18N
        header.add(gradient);
        gradient.setBounds(0, 0, 1080, 170);

        getContentPane().add(header);
        header.setBounds(0, 0, 1080, 170);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new funcAccont().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel gradient;
    private javax.swing.JPanel header;
    private javax.swing.JLabel hello;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
