package template.adm;

import template.client.historico;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natanael-PC
 */
public class verDenuncia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(verDenuncia.class.getName());

    int id;
    
    int denunciadoID;
    int denuncianteID;
    
    /**
     * Creates new form historico
     */
    public verDenuncia() {
        initComponents();
        

    }
    public verDenuncia(int id) {
        initComponents();
        this.id = id;
        denunciaTitle.setText("Denuncia " + id);
        
        //informaçoes puxadas do banco de dados
        int denunciadoID = 0;
        int denuncianteID = 0;
        String _resumo = "";
        
        this.denunciadoID = denunciadoID;
        this.denuncianteID = denuncianteID;
        
        denunciado.setText("Denunciado: " + denunciadoID);
        denunciante.setText("Denunciante: " + denuncianteID);
        resumo.setText(_resumo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        denunciaTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        header = new javax.swing.JPanel();
        gradient = new javax.swing.JLabel();
        denunciado = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        denunciaTitle2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        hitorico_denunciante = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        resumo = new javax.swing.JLabel();
        denunciante = new javax.swing.JLabel();
        historico_Denunciado = new javax.swing.JButton();
        Aprovar = new javax.swing.JButton();
        Negar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        denunciaTitle.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        denunciaTitle.setForeground(new java.awt.Color(102, 102, 102));
        denunciaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        denunciaTitle.setText("Denuncias 001");
        denunciaTitle.setToolTipText("");
        denunciaTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        denunciaTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(denunciaTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1040, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1040, 10));

        header.setBackground(new java.awt.Color(255, 69, 69));
        header.setLayout(null);

        gradient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/red_bg.jpg"))); // NOI18N
        header.add(gradient);
        gradient.setBounds(0, 0, 1080, 170);

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 50));

        denunciado.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        denunciado.setForeground(new java.awt.Color(102, 102, 102));
        denunciado.setText("Denunciado: 0000");
        denunciado.setToolTipText("");
        denunciado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        denunciado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(denunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 880, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1040, 10));

        denunciaTitle2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        denunciaTitle2.setForeground(new java.awt.Color(102, 102, 102));
        denunciaTitle2.setText("Resumo:");
        denunciaTitle2.setToolTipText("");
        denunciaTitle2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        denunciaTitle2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(denunciaTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 880, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1040, 10));

        hitorico_denunciante.setText("ver histórico");
        hitorico_denunciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitorico_denuncianteActionPerformed(evt);
            }
        });
        getContentPane().add(hitorico_denunciante, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 110, -1));

        cancelar.setBackground(new java.awt.Color(204, 204, 204));
        cancelar.setText("Cancelar");
        cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 150, 30));

        resumo.setBackground(new java.awt.Color(255, 255, 255));
        resumo.setText("Resumo");
        resumo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(resumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 990, 200));

        denunciante.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        denunciante.setForeground(new java.awt.Color(102, 102, 102));
        denunciante.setText("Denunciante: 000");
        denunciante.setToolTipText("");
        denunciante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        denunciante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(denunciante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 880, 30));

        historico_Denunciado.setText("ver histórico");
        historico_Denunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historico_DenunciadoActionPerformed(evt);
            }
        });
        getContentPane().add(historico_Denunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 110, -1));

        Aprovar.setBackground(new java.awt.Color(153, 255, 204));
        Aprovar.setText("Aprovar");
        Aprovar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Aprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprovarActionPerformed(evt);
            }
        });
        getContentPane().add(Aprovar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 150, 30));

        Negar.setBackground(new java.awt.Color(255, 102, 102));
        Negar.setForeground(new java.awt.Color(255, 255, 255));
        Negar.setText("Negar");
        Negar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Negar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegarActionPerformed(evt);
            }
        });
        getContentPane().add(Negar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 150, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprovarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AprovarActionPerformed

    private void NegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NegarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        funcAccont targetScreen = new funcAccont();
        this.setVisible(false);
        targetScreen.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void historico_DenunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historico_DenunciadoActionPerformed
        // TODO add your handling code here:
        //usa o id do denunciado para entrar na tela de historico dele
    }//GEN-LAST:event_historico_DenunciadoActionPerformed

    private void hitorico_denuncianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitorico_denuncianteActionPerformed
        // TODO add your handling code here:
         //usa o id do denunciante para entrar na tela de historico dele
    }//GEN-LAST:event_hitorico_denuncianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new verDenuncia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aprovar;
    private javax.swing.JButton Negar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel denunciaTitle;
    private javax.swing.JLabel denunciaTitle2;
    private javax.swing.JLabel denunciado;
    private javax.swing.JLabel denunciante;
    private javax.swing.JLabel gradient;
    private javax.swing.JPanel header;
    private javax.swing.JButton historico_Denunciado;
    private javax.swing.JButton hitorico_denunciante;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel resumo;
    // End of variables declaration//GEN-END:variables
}
