package template;

import template.client.clientAccont;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natanael-PC
 */
public class Index extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Index.class.getName());

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        _______ = new javax.swing.JSeparator();
        Logotipo = new javax.swing.JLabel();
        pageName = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        txtfld_user = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txtfld_senha = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        btn_criarconta = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(246, 246, 246));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 69, 69));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1080, 60);
        getContentPane().add(_______);
        _______.setBounds(80, 190, 930, 10);

        Logotipo.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Logotipo.setForeground(new java.awt.Color(255, 255, 255));
        Logotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logotipo.setText("Safe Bank");
        Logotipo.setToolTipText("");
        Logotipo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(Logotipo);
        Logotipo.setBounds(380, 100, 300, 78);

        pageName.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        pageName.setForeground(new java.awt.Color(255, 255, 255));
        pageName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageName.setText("Login");
        pageName.setToolTipText("");
        pageName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(pageName);
        pageName.setBounds(370, 207, 300, 23);

        lbl_user.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 255, 255));
        lbl_user.setText("User:");
        lbl_user.setToolTipText("");
        lbl_user.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbl_user);
        lbl_user.setBounds(320, 300, 300, 23);

        txtfld_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtfld_user);
        txtfld_user.setBounds(320, 330, 420, 22);

        lbl_senha.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("Senha");
        lbl_senha.setToolTipText("");
        lbl_senha.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbl_senha);
        lbl_senha.setBounds(320, 360, 300, 23);

        txtfld_senha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtfld_senha);
        txtfld_senha.setBounds(320, 390, 420, 22);

        btn_entrar.setBackground(new java.awt.Color(153, 153, 153));
        btn_entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar.setText("Criar Conta");
        btn_entrar.setToolTipText("Preencha os campos e clique aqui para entrar");
        btn_entrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_entrar);
        btn_entrar.setBounds(440, 470, 180, 30);

        btn_criarconta.setBackground(new java.awt.Color(255, 69, 69));
        btn_criarconta.setForeground(new java.awt.Color(255, 255, 255));
        btn_criarconta.setText("Entrar");
        btn_criarconta.setToolTipText("Preencha os campos e clique aqui para entrar");
        btn_criarconta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_criarconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criarcontaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_criarconta);
        btn_criarconta.setBounds(440, 430, 180, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/blur_greyBg.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 60, 1080, 670);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_criarcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarcontaActionPerformed
        String user = txtfld_user.getText();
        String senha = String.valueOf(txtfld_senha.getPassword());
        
        //if(metodo de check login){}
        
        //troca de tela para a tela do cliente
        clientAccont acont = new clientAccont();
        this.setVisible(false);
        acont.setVisible(true);
        
        
    }//GEN-LAST:event_btn_criarcontaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Index().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Logotipo;
    private javax.swing.JSeparator _______;
    private javax.swing.JButton btn_criarconta;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel pageName;
    private javax.swing.JPasswordField txtfld_senha;
    private javax.swing.JTextField txtfld_user;
    // End of variables declaration//GEN-END:variables
}
