package template;

import DAO.ConnectionFactory;
import DAO.UsuarioDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Funcionario;
import model.Sessao;
import model.Usuario;
import template.client.clientAccont;
import template.client.denuncia;
import template.adm.funcAccont;
import template.client.cadastroCliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natanael-PC
 */
public class Index extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Index.class.getName());

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        _______ = new javax.swing.JSeparator();
        Logotipo = new javax.swing.JLabel();
        pageName = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        txtfld_user = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txtfld_senha = new javax.swing.JPasswordField();
        btn_CriarConta = new javax.swing.JButton();
        btn_Entrar = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(246, 246, 246));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 69, 69));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1080, 60);
        getContentPane().add(_______);
        _______.setBounds(80, 190, 930, 10);

        Logotipo.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        Logotipo.setForeground(new java.awt.Color(255, 255, 255));
        Logotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logotipo.setText("Safe Bank");
        Logotipo.setToolTipText("");
        Logotipo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(Logotipo);
        Logotipo.setBounds(380, 100, 300, 78);

        pageName.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        pageName.setForeground(new java.awt.Color(255, 255, 255));
        pageName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageName.setText("Login");
        pageName.setToolTipText("");
        pageName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(pageName);
        pageName.setBounds(370, 207, 300, 24);

        lbl_user.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 255, 255));
        lbl_user.setText("User:");
        lbl_user.setToolTipText("");
        lbl_user.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbl_user);
        lbl_user.setBounds(320, 300, 300, 24);

        txtfld_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtfld_user);
        txtfld_user.setBounds(320, 330, 420, 22);

        lbl_senha.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("Senha");
        lbl_senha.setToolTipText("");
        lbl_senha.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbl_senha);
        lbl_senha.setBounds(320, 360, 300, 24);

        txtfld_senha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtfld_senha);
        txtfld_senha.setBounds(320, 390, 420, 22);

        btn_CriarConta.setBackground(new java.awt.Color(153, 153, 153));
        btn_CriarConta.setForeground(new java.awt.Color(255, 255, 255));
        btn_CriarConta.setText("Criar Conta");
        btn_CriarConta.setToolTipText("Preencha os campos e clique aqui para entrar");
        btn_CriarConta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_CriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CriarContaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CriarConta);
        btn_CriarConta.setBounds(440, 470, 180, 30);

        btn_Entrar.setBackground(new java.awt.Color(255, 69, 69));
        btn_Entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Entrar.setText("Entrar");
        btn_Entrar.setToolTipText("Preencha os campos e clique aqui para entrar");
        btn_Entrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Entrar);
        btn_Entrar.setBounds(440, 430, 180, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/blur_greyBg.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 60, 1080, 670);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarActionPerformed
        String email = txtfld_user.getText();
        String senha = String.valueOf(txtfld_senha.getPassword());
        
        //verifica se todos os campos estao preenchidos
        if(email.equals("") || senha.equals("") || !email.contains("@")){
            
          
            
            JOptionPane.showMessageDialog(null,
                "Email e/ou senha inválidos",
                "Erro de login",
                JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        
        //Luc: Adicionei um try cath aqui pra não ficar crashando em erro quando nao conseguir conectar no banco
        try {
            
            UsuarioDAO dao = new UsuarioDAO();
        
            Usuario user = dao.fazerLogin(email, senha);

            if (user != null) {
                Sessao.setUsuario(user);

                if (user instanceof Cliente) {
                    clientAccont acont = new clientAccont();
                    this.setVisible(false);
                    acont.setVisible(true);
                } else if (user instanceof Funcionario) {
                    funcAccont contaFuncionario = new funcAccont();
                    this.setVisible(false);
                    contaFuncionario.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,
                    "Email ou senha inválidos!",
                    "Erro de login",
                    JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao logar, tente de novo mais tarde",
                    "Erro de login",
                    JOptionPane.ERROR_MESSAGE);
            
        }
       
    }//GEN-LAST:event_btn_EntrarActionPerformed

    private void btn_CriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CriarContaActionPerformed
        cadastroCliente targetScreen = new cadastroCliente();
        this.setVisible(false);
        targetScreen.setVisible(true);
    }//GEN-LAST:event_btn_CriarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Index().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Logotipo;
    private javax.swing.JSeparator _______;
    private javax.swing.JButton btn_CriarConta;
    private javax.swing.JButton btn_Entrar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel pageName;
    private javax.swing.JPasswordField txtfld_senha;
    private javax.swing.JTextField txtfld_user;
    // End of variables declaration//GEN-END:variables
}
