package template.client;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natanael-PC
 */
public class clientAccont extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(clientAccont.class.getName());

    /**
     * Creates new form clientAccont
     */
    public clientAccont() {
        
        //inicializar das informaçoes da tela
        
        initComponents();
        
        String clienteName = "usuário";
        String conta = "000";
        String agencia = "000";
        String acConcat = "Conta: "+ conta+"   |   Agência: "+ conta; //concatenaçao entre conta e agencia
        
        hello.setText("Olá, "+ clienteName);
        dados.setText(acConcat);
        
        double saldo = 100;
        txt_saldo.setText("Saldo: R$"+ saldo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        dados = new javax.swing.JLabel();
        hello = new javax.swing.JLabel();
        gradient = new javax.swing.JLabel();
        txt_saldo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_edit = new javax.swing.JButton();
        btn_transf = new javax.swing.JButton();
        btn_hist = new javax.swing.JButton();
        btn_denun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 69, 69));
        header.setLayout(null);

        dados.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        dados.setForeground(new java.awt.Color(255, 255, 255));
        dados.setText("Conta: 000.000   |   Agência: 00000");
        dados.setToolTipText("");
        dados.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        header.add(dados);
        dados.setBounds(20, 110, 300, 23);

        hello.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        hello.setForeground(new java.awt.Color(255, 255, 255));
        hello.setText("Olá, {user}");
        hello.setToolTipText("");
        hello.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        header.add(hello);
        hello.setBounds(20, 30, 250, 78);

        gradient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/red_bg.jpg"))); // NOI18N
        header.add(gradient);
        gradient.setBounds(0, 0, 1080, 170);

        getContentPane().add(header);
        header.setBounds(0, 0, 1080, 170);

        txt_saldo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txt_saldo.setForeground(new java.awt.Color(102, 102, 102));
        txt_saldo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txt_saldo.setText("Saldo: R$100,00");
        txt_saldo.setToolTipText("");
        txt_saldo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(txt_saldo);
        txt_saldo.setBounds(10, 200, 1040, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 250, 1040, 10);

        btn_edit.setText("<html><h1>Editar Conta");
        btn_edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(70, 360, 300, 70);

        btn_transf.setText("<html><h1>Transferência");
        btn_transf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_transf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transfActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transf);
        btn_transf.setBounds(70, 280, 300, 70);

        btn_hist.setText("<html><h1>Histórico");
        btn_hist.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_hist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_histActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hist);
        btn_hist.setBounds(380, 280, 300, 70);

        btn_denun.setText("<html><h1>Denunciar");
        btn_denun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_denun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_denunActionPerformed(evt);
            }
        });
        getContentPane().add(btn_denun);
        btn_denun.setBounds(690, 280, 300, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed

        editarConta targetScreen = new editarConta();
        
        this.setVisible(false);
        targetScreen.setVisible(true);
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_transfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transfActionPerformed
       transacao targetScreen = new transacao();
       
       this.setVisible(false);
        targetScreen.setVisible(true);
    }//GEN-LAST:event_btn_transfActionPerformed

    private void btn_histActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_histActionPerformed
       historico targetScreen = new historico();
       
       this.setVisible(false);
        targetScreen.setVisible(true);
    }//GEN-LAST:event_btn_histActionPerformed

    private void btn_denunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_denunActionPerformed
       denuncia targetScreen = new denuncia();
       
       this.setVisible(false);
        targetScreen.setVisible(true);
    }//GEN-LAST:event_btn_denunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new clientAccont().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_denun;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hist;
    private javax.swing.JButton btn_transf;
    private javax.swing.JLabel dados;
    private javax.swing.JLabel gradient;
    private javax.swing.JPanel header;
    private javax.swing.JLabel hello;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txt_saldo;
    // End of variables declaration//GEN-END:variables
}
