package template.client;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import Sources.transationCell;
import template.adm.funcAccont;
import template.client.clientAccont;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natanael-PC
 */
public class historico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(historico.class.getName());

    /**
     * Creates new form historico
     */
    boolean isFuncAccont = false; 
    
    transationCell cell[]; //armazena as celulas de transaçao
    public historico() {
        initComponents();
        
       transationCell _cell[] = {new transationCell("001", "002", "02/02/2002", "0001", 100)}; // meio campo pra criar as celulas e depois armazenar elas. Vai precisar de alguma logica pra puxar essas informaçoes do banco de dados de forma volatil
       cell = _cell;
       
        generateGrid();
    }
     public historico(int id, boolean isFunc) {
        initComponents();
        //usa eses pra puaxar informaçoes de um ID expecifico
        
        
       transationCell _cell[] = {new transationCell("001", "002", "02/02/2002", "0001", 100)}; // meio campo pra criar as celulas e depois armazenar elas. Vai precisar de alguma logica pra puxar essas informaçoes do banco de dados de forma volatil
       cell = _cell;
       isFuncAccont = isFunc;
       //isFunc verfica se o usuario que esta entrando é um funcionario ou um cliente
       
        generateGrid();
    }
    
    void generateGrid(){
        int verticalGap = 10; // gap entre as celulas
        
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));
        
        
        //para: // De: // Data: // Cod: // quantia 
        //essa é a sequencia para criar um campo ja preenchido, quando entrar aqui so puxa uma lista do banco de dados com essas informaçoes
        
        
        
        //adiciona as celulas
        int alturaTotal = ((60 + verticalGap))* (cell.length + 1);
        content.setPreferredSize(new Dimension(400, alturaTotal));
        for(transationCell currentCell : cell){
            content.add(Box.createVerticalStrut(verticalGap));
            content.add(currentCell);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        btn_cancelar = new javax.swing.JButton();
        gradient = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        historicoTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 69, 69));
        header.setLayout(null);

        btn_cancelar.setBackground(new java.awt.Color(153, 153, 153));
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Voltar");
        btn_cancelar.setToolTipText("Preencha os campos e clique aqui para entrar");
        btn_cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        header.add(btn_cancelar);
        btn_cancelar.setBounds(960, 10, 100, 20);

        gradient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/red_bg.jpg"))); // NOI18N
        header.add(gradient);
        gradient.setBounds(0, 0, 1080, 170);

        getContentPane().add(header);
        header.setBounds(0, 0, 1080, 50);

        content.setPreferredSize(new java.awt.Dimension(1080, 720));
        content.setLayout(null);
        scroll.setViewportView(content);

        getContentPane().add(scroll);
        scroll.setBounds(0, 140, 1070, 750);

        historicoTitle.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        historicoTitle.setForeground(new java.awt.Color(102, 102, 102));
        historicoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historicoTitle.setText("Histórico");
        historicoTitle.setToolTipText("");
        historicoTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        historicoTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(historicoTitle);
        historicoTitle.setBounds(10, 70, 1040, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 120, 1040, 10);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        
        
        
        if(!isFuncAccont){
            clientAccont targetScreen = new clientAccont();
            this.setVisible(false);
            targetScreen.setVisible(true);
        }
        else{
            funcAccont targetScreen = new funcAccont();
            this.setVisible(false);
            targetScreen.setVisible(true);
        }
       
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new historico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPanel content;
    private javax.swing.JLabel gradient;
    private javax.swing.JPanel header;
    private javax.swing.JLabel historicoTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
