package template.client;

import DAO.ContaDAO;
import DAO.TransacaoDAO;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Conta;
import model.Sessao;
import model.Transacao;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natanael-PC
 */
public class transacao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(transacao.class.getName());

    /**
     * Creates new form transacao
     */
    public transacao() {
        initComponents();
        
        
        Cliente cliente = (Cliente)Sessao.getUsuario();
        
        ContaDAO contaDao = new ContaDAO();
        Conta conta = contaDao.buscarContaPorClienteId(cliente.getClienteId()); // metodo para pegar as informações da conta.
        
        txt_saldo.setText("Saldo: R$" + conta.getSaldo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        pageName = new javax.swing.JLabel();
        gradient = new javax.swing.JLabel();
        txt_saldo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_remetente = new javax.swing.JLabel();
        txtfld_remetente = new javax.swing.JTextField();
        lbl_quantia = new javax.swing.JLabel();
        txtfld_quantia = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txtfld_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 69, 69));
        header.setLayout(null);

        pageName.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        pageName.setForeground(new java.awt.Color(255, 255, 255));
        pageName.setText("Transferência");
        pageName.setToolTipText("");
        pageName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        header.add(pageName);
        pageName.setBounds(10, 130, 300, 24);

        gradient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/red_bg.jpg"))); // NOI18N
        header.add(gradient);
        gradient.setBounds(0, 0, 1080, 170);

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 170));

        txt_saldo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        txt_saldo.setForeground(new java.awt.Color(102, 102, 102));
        txt_saldo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txt_saldo.setText("Saldo: R$100,00");
        txt_saldo.setToolTipText("");
        txt_saldo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(txt_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1040, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1040, 10));

        lbl_remetente.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        lbl_remetente.setForeground(new java.awt.Color(102, 102, 102));
        lbl_remetente.setText("Pix do remetente:");
        lbl_remetente.setToolTipText("");
        lbl_remetente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbl_remetente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 300, -1));

        txtfld_remetente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtfld_remetente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 420, -1));

        lbl_quantia.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        lbl_quantia.setForeground(new java.awt.Color(102, 102, 102));
        lbl_quantia.setText("Quantia:");
        lbl_quantia.setToolTipText("");
        lbl_quantia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbl_quantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 300, -1));

        txtfld_quantia.setText("0");
        txtfld_quantia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtfld_quantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfld_quantiaKeyTyped(evt);
            }
        });
        getContentPane().add(txtfld_quantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 420, -1));

        lbl_senha.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(102, 102, 102));
        lbl_senha.setText("Senha:");
        lbl_senha.setToolTipText("");
        lbl_senha.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbl_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 300, -1));

        btn_enviar.setBackground(new java.awt.Color(255, 69, 69));
        btn_enviar.setForeground(new java.awt.Color(255, 255, 255));
        btn_enviar.setText("Enviar");
        btn_enviar.setToolTipText("Preencha os campos e clique aqui para entrar");
        btn_enviar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 180, 30));

        btn_cancelar.setBackground(new java.awt.Color(153, 153, 153));
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setToolTipText("Preencha os campos e clique aqui para entrar");
        btn_cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 180, 30));

        txtfld_senha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtfld_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
    try {
        String numeroContaDestino = txtfld_remetente.getText().trim(); // chave pix (número da conta)
        double valor = Double.parseDouble(txtfld_quantia.getText());
        String senha = String.valueOf(txtfld_senha.getPassword());

        Cliente cliente = (Cliente) Sessao.getUsuario();
        ContaDAO contaDao = new ContaDAO();
        Conta contaOrigem = contaDao.buscarContaPorClienteId(cliente.getClienteId());

        if (valor <= 0) {
            JOptionPane.showMessageDialog(this,
                "A quantia deve ser maior que zero.",
                "Erro de transação",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (numeroContaDestino.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Todos os campos devem ser preenchidos corretamente.",
                "Erro de transação",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (numeroContaDestino.equals(contaOrigem.getNumeroConta())) {
            JOptionPane.showMessageDialog(this,
                "Você não pode transferir para sua própria conta.",
                "Erro de transação",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!senha.equals(cliente.getSenha())) {
            JOptionPane.showMessageDialog(this,
                "Senha incorreta.",
                "Erro de transação",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buscar conta de destino
        Conta contaDestino = contaDao.buscarContaPorNumero(numeroContaDestino);

        if (contaDestino == null) {
            JOptionPane.showMessageDialog(this,
                "Conta de destino não encontrada.",
                "Erro de transação",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verifica se há saldo suficiente
        if (contaOrigem.getSaldo() < valor) {
            JOptionPane.showMessageDialog(this,
                "Saldo insuficiente.",
                "Erro de transação",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Criar objeto de transação
        Transacao transacao = new Transacao();
        transacao.setContaOrigem(contaOrigem);
        transacao.setContaDestino(contaDestino);
        transacao.setValor(valor);

        // Realizar a transferência
        TransacaoDAO transacaoDAO = new TransacaoDAO();
        boolean sucesso = transacaoDAO.realizarTransferenciaPorNumeroConta(transacao);

        if (sucesso) {
            JOptionPane.showMessageDialog(this,
                "Transferência realizada com sucesso.",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);

            clientAccont targetScreen = new clientAccont();
            this.setVisible(false);
            targetScreen.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                "Erro ao realizar transferência.",
                "Erro de transação",
                JOptionPane.ERROR_MESSAGE);
        }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Valor inválido. Digite apenas números.",
                "Erro de entrada",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erro inesperado: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } 
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       clientAccont targetScreen = new clientAccont();
        this.setVisible(false);
        targetScreen.setVisible(true);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txtfld_quantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfld_quantiaKeyTyped
        char c = evt.getKeyChar();

        // Impede letras
        if (!Character.isDigit(c)) {
            evt.consume();
            return;
        }
    }//GEN-LAST:event_txtfld_quantiaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new transacao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JLabel gradient;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_quantia;
    private javax.swing.JLabel lbl_remetente;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel pageName;
    private javax.swing.JLabel txt_saldo;
    private javax.swing.JTextField txtfld_quantia;
    private javax.swing.JTextField txtfld_remetente;
    private javax.swing.JPasswordField txtfld_senha;
    // End of variables declaration//GEN-END:variables
}
