/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sources;

import template.adm.funcAccont;
import template.adm.verDenuncia;

/**
 *
 * @author Natanael-PC
 */
public class denunCell extends javax.swing.JPanel {

    /**
     * Creates new form transationCell
     */
    int id;
    funcAccont parent;
    
    public denunCell() {
        initComponents();
    }
    public denunCell(String _denunciado, String _data, int _id) {
        initComponents();

        denunciado.setText("Para: " + _denunciado);
        data.setText("Data: " + _data);
        this.id = _id;
        this.parent = funcAccont.funcScreen;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        denunciado = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        verMais = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(900, 50));
        setMinimumSize(new java.awt.Dimension(900, 50));
        setPreferredSize(new java.awt.Dimension(900, 50));

        denunciado.setText("User: 000");

        data.setText("data: 00/00/0000");

        verMais.setText("ver mais");
        verMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(denunciado)
                .addGap(181, 181, 181)
                .addComponent(data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(verMais)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denunciado)
                    .addComponent(data)
                    .addComponent(verMais))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMaisActionPerformed
        verDenuncia targetScreen = new verDenuncia(id);
        parent.setVisible(false);
        targetScreen.setVisible(true);
    }//GEN-LAST:event_verMaisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data;
    private javax.swing.JLabel denunciado;
    private javax.swing.JButton verMais;
    // End of variables declaration//GEN-END:variables
}
