/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sources;

import java.util.Date;

/**
 *
 * @author Natanael-PC
 */
public class transationCell extends javax.swing.JPanel {

    /**
     * Creates new form transationCell
     */
    public transationCell() {
        initComponents();
    }
     public transationCell(String _destinatario, String _remetente, Date _data, long _cod, double _quantia, long prot) {
        initComponents();
       
        
        destinatario.setText("Para: " + _destinatario);
        remetente.setText("De: " + _remetente);
        data.setText(_data.toString());
        id.setText(String.valueOf(_cod));
        quantia.setText("R$" + String.valueOf(_quantia));
        protocolo.setText(String.valueOf(prot));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destinatario = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        quantia = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        remetente = new javax.swing.JLabel();
        protocolo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(900, 50));
        setMinimumSize(new java.awt.Dimension(900, 50));
        setPreferredSize(new java.awt.Dimension(900, 50));

        destinatario.setText("Para: 0000");

        data.setText("data: 00/00/0000");

        quantia.setText("Quantia: 100");

        id.setText("Cod: 00000");

        remetente.setText("de: 0000");

        protocolo.setText("Cod: 00000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(destinatario)
                .addGap(65, 65, 65)
                .addComponent(remetente)
                .addGap(73, 73, 73)
                .addComponent(data)
                .addGap(114, 114, 114)
                .addComponent(quantia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(id)
                .addGap(109, 109, 109)
                .addComponent(protocolo)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinatario)
                    .addComponent(data)
                    .addComponent(quantia)
                    .addComponent(id)
                    .addComponent(remetente)
                    .addComponent(protocolo))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data;
    private javax.swing.JLabel destinatario;
    private javax.swing.JLabel id;
    private javax.swing.JLabel protocolo;
    private javax.swing.JLabel quantia;
    private javax.swing.JLabel remetente;
    // End of variables declaration//GEN-END:variables
}
